controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    fts_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

fts_broadcaster:
  ros__parameters:
    sensor_name: kwr75_force_sensor
    frame_id: fts_link